import os
import json


udaan_vendor = json.loads(os.environ['Z_UDAAN_VENDOR_INFO'])
UDAAN_ADVERTISING_AND_MARKETING_ACCOUNT_ID = os.environ['Z_UDAAN_ADVERTISING_AND_MARKETING_ACCOUNT_ID']
IGST_18_TAX_ID = os.environ['Z_IGST_18_TAX_ID']
SAC_SALES_MARKETING = os.environ['Z_SAC_SALES_MARKETING']
HIVELOOP_LOGISTICS_PAYMENT_ACCOUNT = os.environ['Z_HIVELOOP_LOGISTICS_PAYMENT_ACCOUNT']
HIVELOOP_LOGISTICS_VENDOR_ID = os.environ['Z_HIVELOOP_LOGISTICS_VENDOR_ID']
ICICI_ACCOUNT_ID = os.environ['Z_ICICI_ACCOUNT_ID']
RTO_CLAIM_DUMMY_CUSTOMER_ID = os.environ['Z_RTO_CLAIM_DUMMY_CUSTOMER_ID']
ADVERTISEMENT_CHARGES_ITEM_ID = os.environ['Z_ADVERTISEMENT_CHARGES_ITEM_ID']
LOGISTICS_CHARGES_ITEM_ID = os.environ['Z_LOGISTICS_CHARGES_ITEM_ID']

